package org.omegacode.helloworldservice.wsdl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

import org.omegacode.helloworldservice.schema.Mensagem;
import org.omegacode.helloworldservice.schema.NumeroCartao;

/**
 * A operacao digaOla recebe um NumeroCartao por parametro e
 * 			devolve um cumprimento ou erro em situacoes especificas
 * 		
 *
 * This class was generated by Apache CXF 2.7.0
 * 2014-03-13T20:49:14.266-03:00
 * Generated source version: 2.7.0
 * 
 */
@WebService(targetNamespace = "http://helloworldservice.omegacode.org/wsdl/", name = "DigaOla_PortType")
@XmlSeeAlso({ObjectFactory.class, org.omegacode.helloworldservice.schema.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface DigaOlaPortType {

    @WebResult(name = "mensagem", targetNamespace = "", partName = "mensagem")
    @WebMethod
    public Mensagem message(
        @WebParam(partName = "parametro", name = "parametro", targetNamespace = "")
        NumeroCartao parametro
    ) throws StatusException;
}
