
package org.omegacode.helloworldservice.wsdl;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;

import org.omegacode.helloworldservice.schema.Mensagem;
import org.omegacode.helloworldservice.schema.NumeroCartao;

/**
 * This class was generated by Apache CXF 2.7.0
 * 2014-03-13T20:49:14.220-03:00
 * Generated source version: 2.7.0
 * 
 */
public final class DigaOlaPortType_HelloWorldServicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://helloworldservice.omegacode.org/wsdl/", "HelloWorldService");

    private DigaOlaPortType_HelloWorldServicePort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = HelloWorldService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        HelloWorldService ss = new HelloWorldService(wsdlURL, SERVICE_NAME);
        DigaOlaPortType port = ss.getHelloWorldServicePort();  
        
        {
        System.out.println("Invoking message...");
        NumeroCartao _message_parametro = null;
        try {
            Mensagem _message__return = port.message(_message_parametro);
            System.out.println("message.result=" + _message__return);

        } catch (StatusException e) { 
            System.out.println("Expected exception: StatusException has occurred.");
            System.out.println(e.toString());
        }
            }

        System.exit(0);
    }

}
