
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package org.omegacode.helloworldservice.wsdl;

import java.util.logging.Logger;

import org.omegacode.helloworldservice.schema.Mensagem;
import org.omegacode.helloworldservice.schema.NumeroCartao;

/**
 * This class was generated by Apache CXF 2.7.0
 * 2014-03-13T20:49:14.252-03:00
 * Generated source version: 2.7.0
 * 
 */

@javax.jws.WebService(
                      serviceName = "HelloWorldService",
                      portName = "HelloWorldService_Port",
                      targetNamespace = "http://helloworldservice.omegacode.org/wsdl/",
                      wsdlLocation = "file:/home/washington/dev/projects/spring-batch-example/workspace/spring-batch/spring-batch-example/src/main/resources/HelloWorldService.wsdl",
                      endpointInterface = "org.omegacode.helloworldservice.wsdl.DigaOlaPortType")
                      
public class DigaOlaPortTypeImpl implements DigaOlaPortType {

    private static final Logger LOG = Logger.getLogger(DigaOlaPortTypeImpl.class.getName());

    /* (non-Javadoc)
     * @see org.omegacode.helloworldservice.wsdl.DigaOlaPortType#message(org.omegacode.helloworldservice.wsdl.NumeroCartao  parametro )*
     */
    public Mensagem message(NumeroCartao parametro) throws StatusException    { 
        LOG.info("Executing operation message");
        System.out.println(parametro);
        try {
            Mensagem _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new StatusException("StatusException...");
    }

}
