package org.omegacode.helloworldservice.wsdl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.0
 * 2014-03-13T20:49:14.278-03:00
 * Generated source version: 2.7.0
 * 
 */
@WebServiceClient(name = "HelloWorldService", 
                  wsdlLocation = "file:/home/washington/dev/projects/spring-batch-example/workspace/spring-batch/spring-batch-example/src/main/resources/HelloWorldService.wsdl",
                  targetNamespace = "http://helloworldservice.omegacode.org/wsdl/") 
public class HelloWorldService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://helloworldservice.omegacode.org/wsdl/", "HelloWorldService");
    public final static QName HelloWorldServicePort = new QName("http://helloworldservice.omegacode.org/wsdl/", "HelloWorldService_Port");
    static {
        URL url = null;
        try {
            url = new URL("file:/home/washington/dev/projects/spring-batch-example/workspace/spring-batch/spring-batch-example/src/main/resources/HelloWorldService.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(HelloWorldService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/home/washington/dev/projects/spring-batch-example/workspace/spring-batch/spring-batch-example/src/main/resources/HelloWorldService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public HelloWorldService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public HelloWorldService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HelloWorldService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public HelloWorldService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public HelloWorldService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public HelloWorldService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns DigaOlaPortType
     */
    @WebEndpoint(name = "HelloWorldService_Port")
    public DigaOlaPortType getHelloWorldServicePort() {
        return super.getPort(HelloWorldServicePort, DigaOlaPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DigaOlaPortType
     */
    @WebEndpoint(name = "HelloWorldService_Port")
    public DigaOlaPortType getHelloWorldServicePort(WebServiceFeature... features) {
        return super.getPort(HelloWorldServicePort, DigaOlaPortType.class, features);
    }

}
