
package org.omegacode.helloworldservice.wsdl;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.0
 * 2014-03-13T20:49:14.244-03:00
 * Generated source version: 2.7.0
 */

@WebFault(name = "StatusException", targetNamespace = "http://helloworldservice.omegacode.org/schema/")
public class StatusException extends Exception {
    
    private org.omegacode.helloworldservice.schema.Erro statusException;

    public StatusException() {
        super();
    }
    
    public StatusException(String message) {
        super(message);
    }
    
    public StatusException(String message, Throwable cause) {
        super(message, cause);
    }

    public StatusException(String message, org.omegacode.helloworldservice.schema.Erro statusException) {
        super(message);
        this.statusException = statusException;
    }

    public StatusException(String message, org.omegacode.helloworldservice.schema.Erro statusException, Throwable cause) {
        super(message, cause);
        this.statusException = statusException;
    }

    public org.omegacode.helloworldservice.schema.Erro getFaultInfo() {
        return this.statusException;
    }
}
